# Generated by Django 2.1.7 on 2019-03-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190315_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
